"""
level.py — Generated 15x15 (5 worms)

Auto-generated by generator.py  (seed 2852404438)
Solve order: E -> D -> C -> B -> A
"""

LEVEL_DATA = {
    "name": "Generated 15x15 (5 worms)",
    "rows": 15,
    "cols": 15,
    "grid": [
        "...............",
        "....c..........",
        "....cc.........",
        ".....cc...aaaa.",
        "......c...aaaa.",
        "......c...aaA..",
        "......c........",
        ".....cc........",
        ".....cC........",
        "......bb.......",
        "......Bbbbbb...",
        "......ee.dd....",
        "......eE.ddddd.",
        ".........ddDdd.",
        "...............",
    ],
    "worms": {
        "A": {"color": "red",   "direction": "down"},
        "B": {"color": "blue",   "direction": "down"},
        "C": {"color": "green",   "direction": "right"},
        "D": {"color": "yellow",   "direction": "down"},
        "E": {"color": "magenta",   "direction": "down"},
    },
}
