name: Project Issue
description: Track tasks, bugs, ideas, or research notes for the game testing & difficulty assessment project
title: "[Issue]: "
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        This issue tracks work related to the game testing and difficulty assessment project.
        It may correspond to implementation, experiments, evaluation, or thesis-related tasks.

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue type
      options:
        - Task (implementation / setup)
        - Bug (framework, environment, tooling)
        - Improvement (method, metric, pipeline)
        - Research (reading, critique, comparison)
        - Documentation / Thesis
        - Other
    validations:
      required: true

  - type: input
    id: related_component
    attributes:
      label: Related component / module
      placeholder: |
        e.g. Learning layer (RL),
        Difficulty metrics,
        Multi-agent coordination,
        Thesis – Methodology,
        Thesis – Related Work
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the task, problem, or observation?
      placeholder: |
        Example:
        - Read the thesis proposal and assess whether methodology and evaluation plan are complete
        - Identify missing components (datasets, baselines, metrics, experiments)
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Planned approach / notes
      description: Thoughts, critiques, or next steps.
      placeholder: |
        Example:
        - Compare proposed framework with Ferdous et al. (2022, 2025)
        - Check if difficulty indicators are operationalized clearly
        - Note missing evaluation or unclear assumptions
    validations:
      required: false

  - type: textarea
    id: related_links
    attributes:
      label: Related files / folders (links)
      description: GitHub links to thesis, notes, code, or experiments.
      placeholder: |
        https://github.com/USERNAME/REPO/tree/main/documentation/thesis_proposal
        https://github.com/USERNAME/REPO/tree/main/experiments
    validations:
      required: false

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance criteria
      options:
        - label: Task completed / analysis finished
        - label: Findings written or summarized
        - label: Action items identified
        - label: Supervisor reviewed / discussed (if applicable)
