"""
level_04.py — Generated 5x5 (5 worms)

Auto-generated by generator.py  (seed 2891909218)
Solve order: E -> D -> C -> B -> A
"""

LEVEL_DATA = {
    "name": "Generated 5x5 (5 worms)",
    "rows": 5,
    "cols": 5,
    "grid": [
        ".bb.e",
        ".DbCe",
        ".dBcE",
        ".dAc.",
        "aaac.",
    ],
    "worms": {
        "A": {"color": "red",   "direction": "up"},
        "B": {"color": "blue",   "direction": "right"},
        "C": {"color": "green",   "direction": "right"},
        "D": {"color": "yellow",   "direction": "left"},
        "E": {"color": "magenta",   "direction": "down"},
    },
}
